import styles from './formulario.module.css'
import Head from 'next/head'

export default function Formulario() {
  
  function botao(){
    alert("Mensagem enviada com sucesso!")
  }
  
  return (
      <div className ={styles.form}>
        <Head>
          <title>Formulario</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
         
        <h1 className = {styles.fale}> Fale conosco!</h1>
        
        <form className = {styles.formulario}>
         <ul> <label for="nome">Nome:</label>
          <input className = {styles.nome} id="nome"/>
        </ul>

        <ul>
          <label for="parte1">Email:</label>
          <input className = {styles.email} id="parte1"/>

          </ul>

          <ul> <label for="parte2">Tel:</label>
          <input className = {styles.telefone} id="parte2"/>
        </ul>

        <ul>
          <label for="parte3">Mens:</label>
          <input className = {styles.mensagem} id="parte3"/>

          </ul>

          <button className = {styles.botao} onClick = {botao}>Enviar!</button>
          <h2></h2>
        </form>
      </div>
    )
}