import Head from 'next/head'
import Image from 'next/image'
import styles from './projeto.module.css'
import { useEffect, useState } from 'react'
import {useRouter} from 'next/router';

export default function PostItem() {
    const router = useRouter();
    const {id} = router.query
    const [projeto, setProjeto] = useState([])

    useEffect(() => {
      obterProjetos()
    }, [id])

    const obterProjetos = async() => {
      const projetos = await fetch('/projetos.json')
      const resultado = await projetos.json()
      for(let projeto of resultado.projects) {
        if(projeto.id == id) {
          setProjeto(projeto)
          break
        }
      }
    }

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.cabecalho}></header>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          <div>
             <h1>{projeto.name}</h1>
             < p className = {styles.texto}><strong>Criado por: </strong>{projeto.createdBy} </p>        
             <p>{projeto.description}</p>
             <p className = {styles.texto}><strong></strong>{projeto.categories}</p>
             <p className = {styles.texto}><strong>Criado em:</strong> {projeto.completedOn}</p>
          </div>
          
           

        </h1>
      </main>
      <footer className={styles.rodape}></footer> 
    </div>
  )
}
