import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Inicio from './Inicio'
import Projetos from './Projetos/index.js'
import Formulario from './Inicio/formulario.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portifolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      
      <Inicio/>
      <Projetos/>
      <Formulario/>
    </div>
  )
}
